export const SET_EXCHANGE_RATES = "SET_EXCHANGE_RATES";
export const SET_BASE_CURRENCY = "SET_BASE_CURRENCY";
export const SET_CONVERTED_CURRENCY = "SET_CONVERTED_CURRENCY";
export const HANDLE_BASE_PRICE_CHANGE = "HANDLE_BASE_PRICE_CHANGE";
export const HANDLE_CONVERT_CURRENCY = "HANDLE_CONVERT_CURRENCY";
